# Generated by Django 4.1.1 on 2022-10-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact_book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact_book",
            name="phone",
            field=models.CharField(max_length=20),
        ),
    ]
