# Generated by Django 4.1.3 on 2022-12-06 14:55

from django.db import migrations, models

import apps.contact_book.models


class Migration(migrations.Migration):

    dependencies = [
        ("contact_book", "0003_contact_book_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("birthday", models.DateField()),
                ("password", models.CharField(max_length=100)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        max_length=265,
                        null=True,
                        upload_to=apps.contact_book.models.get_icon_path,
                    ),
                ),
            ],
        ),
    ]
